name: Python CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Linter avec pylint
      run: |
        pylint simple_math.py test_simple_math.py || true

    - name: Lancer les tests
      run: python -m unittest discover

    - name: Build Docker image
      run: docker build -t tp-ci-cd .

